### ISSUE TITLE
Last contact note as a body of contact reminder notification

### ISSUE THREAD

**Issue by radeklat** [mbarta/SmartContactReminder#9]
It could be useful to display note from last contact log as a body of the contact reminder notification. Example:

**Time to contact Milan Bárta**
Vacation in Rome, baby born, wife promoted

This would provide a quick context to what you spoke about last time. 

This functionality would largely depend on individual notifications being implemented and would not work if more people would be displayed in one notification.

**Comment by radeklat** [comment]
Implemented in 0.5.2

**Comment by radeklat** [comment]
Functionality not present on summary notification.

**Comment by radeklat** [comment]
![screenshot_20180904-115358 01](https://user-images.githubusercontent.com/7273178/45076352-d73c8d00-b0e1-11e8-92ef-264e4dcfeb3e.jpg)

**Comment by mbarta** [comment]
Fixed in 0.5.3
